const mongoose = require('mongoose');
const { randomUUID } = require('crypto');

const studentSchema = new mongoose.Schema({
  // A stable public id, separate from Mongo's _id, so the frontend never
  // has to deal with ObjectId formatting and this could be swapped to a
  // different id scheme later without touching the API shape.
  studentId: {
    type: String,
    required: true,
    unique: true,
    default: () => randomUUID(),
  },
  classId: { type: String, required: true, index: true },
  fullName: { type: String, required: true, trim: true },
  // The primary display name — now required since the UI emphasises
  // nickname over fullName. Still stored as optional at the schema level
  // so existing rows without one don't break on validation.
  nickname: { type: String, default: '', trim: true },
  // A freeform label the teacher can assign (e.g. "Red group", "Morning").
  // Purely for organisation — no functional behaviour is keyed off it.
  group: { type: String, default: '', trim: true },
  // 6-character alphanumeric code generated by the frontend. Used for
  // student auto-login via the /p/:code route. Unique across all classes.
  // NOT required at the schema level — existing students without codes
  // must remain valid. The POST endpoint enforces it for new students.
  code: {
    type: String,
    unique: true,
    sparse: true, // allows multiple nulls (students without codes yet)
    trim: true,
    uppercase: true,
    maxlength: 6,
  },
  createdAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model('Student', studentSchema);
